# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot/protobuf/iot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iot/protobuf/iot.proto',
  package='iot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16iot/protobuf/iot.proto\x12\x03iot\",\n\x06Shades\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\x03\x12\x11\n\tpositions\x18\x02 \x03(\x05\x62\x06proto3')
)




_SHADES = _descriptor.Descriptor(
  name='Shades',
  full_name='iot.Shades',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chat_id', full_name='iot.Shades.chat_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='positions', full_name='iot.Shades.positions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Shades'] = _SHADES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Shades = _reflection.GeneratedProtocolMessageType('Shades', (_message.Message,), {
  'DESCRIPTOR' : _SHADES,
  '__module__' : 'iot.protobuf.iot_pb2'
  # @@protoc_insertion_point(class_scope:iot.Shades)
  })
_sym_db.RegisterMessage(Shades)


# @@protoc_insertion_point(module_scope)
